Court/Controllers/CourtController.cs
using Court.Models;
using CourtDataStorage;
using CourtDataStorage.Tables;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace Court.Controllers
{
    public class CourtController : Controller
    {
        CourtManager manager = new CourtManager(false);

        CourtUser currentUser = null;

        CourtUser CurrentUser
        {
            get
            {
                //currentUser = null;
                if (currentUser == null)
                {
                    currentUser = manager.FindUserByName(User.Identity.Name);
                }
                return currentUser;
            }
        }

        // GET: Court
        [Authorize]
        public ActionResult Index()
        {
            if (CurrentUser.Level == AccessLevel.User)
            {
                if (CurrentUser.Cases != null)
                    return View(CurrentUser.Cases.ToList());
                else
                    return View(new List<CourtCase>());
            }
            else
            {
                return View("Secretary", manager.GetAllCases());
            }
        }
        [Authorize]
        public ActionResult NewCase()
        {
            if (Session["court-case"] == null)
            {
                Session["court-case"] = new CourtCase();
            }
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddIndividual(IndividualModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewCase", model);
            }
            else
            {
                CourtCase courtCase = new CourtCase();
                courtCase.Claimant = new Participant()
                {
                    Individual = model.ToIndividual(manager)
                };
                Session["court-case"] = courtCase;
            }
            return Redirect("/Court/NewRespondent");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddJuridicial(JuridicialModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewCase", model);
            }
            else
            {
                CourtCase courtCase = new CourtCase();
                courtCase.Claimant = new Participant()
                {
                    Juridical = model.ToJuridical(manager)
                };
                Session["court-case"] = courtCase;
            }
            return Redirect("/Court/NewRespondent");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddPhysical(PhysicalModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewCase", model);
            }
            else
            {
                CourtCase courtCase = new CourtCase();
                courtCase.Claimant = new Participant()
                {
                    Physical = model.ToPhysical(manager)
                };
                Session["court-case"] = courtCase;
            }
            return Redirect("/Court/NewRespondent");
        }

        [Authorize]
        public ActionResult NewRespondent()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddIndividualRespondent(IndividualModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewRespondent", model);
            }
            else
            {

                CourtCase courtCase = Session["court-case"] as CourtCase;
                if (courtCase.Respondents == null)
                    courtCase.Respondents = new List<Participant>();
                courtCase.Respondents.Add(new Participant()
                {
                    Individual = model.ToIndividual(manager),
                });

            }
            return Redirect("/Court/NewRespondent");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddJuridicalRespondent(JuridicialModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewRespondent", model);
            }
            else
            {
                CourtCase courtCase = Session["court-case"] as CourtCase;
                if (courtCase.Respondents == null)
                    courtCase.Respondents = new List<Participant>();
                courtCase.Respondents.Add(new Participant()
                {
                    Juridical = model.ToJuridical(manager),
                });

            }
            return Redirect("/Court/NewRespondent");
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddPhysicalRespondent(PhysicalModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewRespondent", model);
            }
            else
            {
                CourtCase courtCase = Session["court-case"] as CourtCase;
                if (courtCase.Respondents == null)
                    courtCase.Respondents = new List<Participant>();
                courtCase.Respondents.Add(new Participant()
                {
                    Physical = model.ToPhysical(manager),
                });

            }
            return Redirect("/Court/NewRespondent");

        }

        [Authorize]
        public ActionResult NewClaim()
        {
            CourtCase courtCase = Session["court-case"] as CourtCase;
            if (courtCase == null || courtCase.Claimant == null || courtCase.Respondents == null || courtCase.Respondents.Count == 0)
                return Redirect("/Court/Index");
            else
                return View();
        }

        [Authorize]
        public ActionResult SaveClaim(ClaimModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("NewClaim", model);
            }
            else
            {
                CourtCase courtCase = Session["court-case"] as CourtCase;
                courtCase.Claim = model.ToClaim(manager);
                courtCase.CourtUser = CurrentUser;
                courtCase.SubmissionDate = DateTime.Now;
                courtCase = manager.AddCourtCase(courtCase);
                currentUser = null;
                return Redirect("/Court/Index");
            }
        }

        [Authorize]
        public ActionResult Resolve(int id)
        {
            if (CurrentUser.Level == AccessLevel.User)
                return View("ViewCase", new ForwardModel()
                {
                    CaseId = id
                });
            else
            {
                CourtCase cCase = manager.GetCase(id);
                return View("ForwardCase", new ForwardModel()
                {
                    CaseId = id,
                    ActionId = (int)cCase.Decision,
                    Comments = cCase.Commentary,
                    Date = cCase.GatheringDate,
                    AttachmentName = cCase.AttachmentName
                });
            }
        }
        [Authorize]
        [HttpPost]
        public ActionResult Resolve(ForwardModel model)
        {
            if (CurrentUser.Level == AccessLevel.User)
                return Redirect("/Court/Index");
            else
            {
                if (model.ActionId == 2 && String.IsNullOrEmpty(model.Comments))
                {
                    ModelState.AddModelError("", "При отклонении иска комментарий обязателен");
                    return View("ForwardCase", model);
                }
                if (model.ActionId == 1 && !model.Date.HasValue)
                {
                    ModelState.AddModelError("", "При принятии иска дата заседания должна быть указана");
                    return View("ForwardCase", model);
                }
                if (model.ActionId == 2 && model.Date.HasValue)
                {
                    ModelState.AddModelError("", "При отклонении иска дата заседания должна быть пустая");
                    return View("ForwardCase", model);
                }
                CourtCase courtCase = manager.GetCase(model.CaseId);
                byte[] data = null;
                string fileName = null;
                if (model.Attachment != null && model.Attachment.ContentLength > 0)
                {
                    using (BinaryReader binaryReader = new BinaryReader(model.Attachment.InputStream))
                    {
                        data = binaryReader.ReadBytes(model.Attachment.ContentLength);
                        fileName = model.Attachment.FileName;
                    }
                }
                manager.UpdateCase(model.CaseId, (Decision)model.ActionId, model.Comments, model.Date, data, fileName);
                return Redirect("/Court/Index");
            }
        }

        [Authorize]
        public ActionResult CountryList()
        {
            if (CurrentUser.Level == AccessLevel.Administrator)
            {
                return View(manager.GettAllAvailableCountries());
            }
            else
            {
                return Redirect("/Court/Index");
            }
        }

        [Authorize]
        public ActionResult DeleteCountry(int id)
        {
            if (CurrentUser.Level == AccessLevel.Administrator)
            {
                manager.DeleteCountry(id);
                return Redirect("/Court/CountryList");
            }
            else
            {
                return Redirect("/Court/Index");
            }
        }

        [Authorize]
        [HttpPost]
        public ActionResult EditCountry(Country model)
        {
            if (CurrentUser.Level == AccessLevel.Administrator)
            {
                manager.EditCountry(model.Id, model.Name);
                return Redirect("/Court/CountryList");
            }
            else
            {

Court/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Приложение АСТРА</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item subbutton">@Html.ActionLink("Главная страница", "Index", "Home", new { area = "" }, null)</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item subbutton">@Html.ActionLink("Личный кабинет", "Index", "Court", new { area = "" }, null)</li>
                        if (Session["isAdmin"] != null && (bool)Session["isAdmin"])
                        {
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle subbutton" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Списки <span class="caret"></span></a>
                                <ul class="dropdown-menu">
                                    <li class="subbutton">@Html.ActionLink("Пользователи", "UserList", "Account", new { area = "" }, null)</li>
                                    <li class="subbutton">@Html.ActionLink("Страны", "CountryList", "Court", new { area = "" }, null)</li>
                                    <li class="subbutton">@Html.ActionLink("Коллегии", "CollegiateList", "Court", new { area = "" }, null)</li>
                                    <li class="subbutton">@Html.ActionLink("Причины споров", "ReasonList", "Court", new { area = "" }, null)</li>
                                </ul>
                            </li>
                        }
                    }
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item subbutton"><div class="username">@User.Identity.Name</div></li>
                        <li class="nav-item subbutton">@Html.ActionLink("Выйти", "Logout", "Account", new { area = "" }, null)</li>
                    }
                    else
                    {
                        <li class="nav-item subbutton">@Html.ActionLink("Авторизация", "Login", "Account", new { area = "" }, null)</li>
                        <li class="nav-item subbutton">@Html.ActionLink("Регистрация", "Registration", "Account", new { area = "" }, null)</li>
                    }
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Приложение АСТРА</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
</body>
</html>